language: python

# Run jobs on container-based infrastructure, can be overridden per job
dist: xenial

# Run builds for both master and topology (and PRs to each)
branches:
  only:
  - master
  - /.*0-branch$/
  - /.*patch-1$/
install:
  - ls
